//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QQZoneParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class QQData
    {
        public Nullable<int> qqNum { get; set; }
        public string nickName { get; set; }
        public Nullable<System.DateTime> publishTime { get; set; }
        public string text { get; set; }
        public string dataIndex { get; set; }
    }
}
